export enum MessageCode {
  // Auth
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  
  // User
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  
  // Exercise
  EXERCISE_CREATED = 'EXERCISE_CREATED',
  EXERCISE_UPDATED = 'EXERCISE_UPDATED',
  EXERCISE_DELETED = 'EXERCISE_DELETED',
  EXERCISE_NOT_FOUND = 'EXERCISE_NOT_FOUND',
  
  // Workout
  WORKOUT_CREATED = 'WORKOUT_CREATED',
  WORKOUT_UPDATED = 'WORKOUT_UPDATED',
  WORKOUT_DELETED = 'WORKOUT_DELETED',
  WORKOUT_NOT_FOUND = 'WORKOUT_NOT_FOUND',
  
  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  REQUIRED_FIELD = 'REQUIRED_FIELD',
  
  // Generic
  GENERIC_ERROR = 'GENERIC_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
}